# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Piráti Střední čechy
email: frantisek.kopriva@pirati.cz
description: > # this means to ignore newlines until "baseurl:"
    Piráti Středočeský kraj
baseurl: "" # the subpath of your site, e.g. /blog  http://stackoverflow.com/questions/16316311/github-pages-and-relative-paths/19173888#19173888
url: "http://strednicechy.pirati.cz" # the base hostname & protocol for your site

mailchimp:
  newsletter:
    action: https://pirati.us9.list-manage.com/subscribe/post?u=7e063d6dffdb0316b906e1351&amp;id=6c882fdc40"
    captcha: b_7e063d6dffdb0316b906e1351_6c882fdc40
  volunters:
    action: https://pirati.us9.list-manage.com/subscribe/post?u=7e063d6dffdb0316b906e1351&amp;id=a9ccc90da1
    captcha: b_7e063d6dffdb0316b906e1351_a9ccc90da1

title_page:
  video: https://www.youtube.com/embed/pWK515EHyG0
  calendar: https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;mode=AGENDA&amp;height=500&amp;wkst=2&amp;hl=cs&amp;bgcolor=%23FFFFFF&amp;src=rm0h4oqjk2j2o0615sc4d1slfk%40group.calendar.google.com&amp;color=%23B1365F&amp;src=lpvmfpogihrca3lqs9p2udae0k%40group.calendar.google.com&amp;color=%238D6F47&amp;ctz=Europe%2FPrague

kontakt:
  map: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d10239.994608957739!2d14.4421077!3d50.0863121!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x317d7c609cbfe9da!2zUGlyw6F0c2vDqSBjZW50cnVtLCBzw61kbG8gxIxlc2vDqSBwaXLDoXRza8OpIHN0cmFueQ!5e0!3m2!1scs!2scz!4v1466169010418

permalink: /blog/:title/
collections:
  people:
    output: true
    permalink: /lide/:path/

gems:
  - jekyll-paginate
paginate_path: "/blog/page:num/"
paginate: 12

# Build settings
markdown: kramdown

cdn_libs:
    css:
      - //cdnjs.cloudflare.com/ajax/libs/foundation/6.2.0/foundation.min.css
      - //cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css
      - //cdnjs.cloudflare.com/ajax/libs/motion-ui/1.2.2/motion-ui.min.css
    js:
      - https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.0/foundation.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/motion-ui/1.2.2/motion-ui.min.js
